site_name: JamCore Mod Wiki
site_description: Information about JamCore Modding's mods and APIs.
site_url: https://docs.jamalam.tech/
site_author: The JamCore Modding Team

repo_url: https://github.com/JamCoreModding/docs
repo_name: JamCoreModding/docs

nav:
  - Home: index.md
  - Auto Recipe:
      - Introduction to Auto Recipe: auto-recipe/about.md
      - Getting Started with Auto Recipe: auto-recipe/getting-started.md
  - Totally Balanced Bone Drops:
      - Introduction to Totally Balanced Bone Drops: totally-balanced-bone-drops/about.md
      - Configuring Totally Balanced Bone Drops: totally-balanced-bone-drops/configuration.md
  - Utility Belt:
      - Introduction to Utility Belt: utility-belt/about.md
      - Configuring Utility Belt: utility-belt/configuration.md
  - RightClickHarvest:
      - Introduction to RightClickHarvest: right-click-harvest/about.md
      - Configuring RightClickHarvest: right-click-harvest/configuration.md
      - Information for Developers & Modpack Creators:
        - Depending on RightClickHarvest: right-click-harvest/developers/depending.md
        - Tags: right-click-harvest/developers/tags.md
        - API: right-click-harvest/developers/api.md
  - Tutorial Lib:
      - Introduction to Tutorial Lib: tutorial-lib/about.md
      - Getting Started with Tutorial Lib: tutorial-lib/getting-started.md
      - Creating a Custom Stage: tutorial-lib/stages.md
      - Creating a Custom Toast: tutorial-lib/toasts.md

theme:
  name: material
  custom_dir: overrides
  logo: assets/JamCoreModding.png
  favicon: assets/JamCoreModding.png
  language: en

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.share
    - content.code.annotate
    
  palette:
    scheme: slate
    primary: red
    accent: amber

plugins:
  - search
  - social
  - git-revision-date-localized:
      type: timeago

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  homepage: https://github.com/JamCoreModding

  social:
    - icon: fontawesome/brands/discord
      link: https://discord.jamalam.tech
    - icon: fontawesome/brands/github
      link: https://github.com/JamCoreModding
    - icon: fontawesome/solid/feather
      link: https://maven.jamalam.tech

