site_name: JamCore Wiki
site_description: Information about JamCore Modding's mods and APIs.
site_url: https://docs.jamalam.tech/
site_author: The JamCore Modding Team

repo_url: https://github.com/JamCoreModding/docs
repo_name: JamCoreModding/docs

nav:
  - Welcome: index.md
  - JamLib:
      - Getting Started: jamlib/getting-started.md
      - Config API: jamlib/config-api.md
      - Mod Reposts: jamlib/mod-reposts.md
  - RightClickHarvest:
      - Introduction: right-click-harvest/about.md
      - Configuring RightClickHarvest: right-click-harvest/configuration.md
      - Tags: right-click-harvest/tags.md
      - API: right-click-harvest/api.md
  - Totally Balanced Bone Drops:
      - Introduction to Totally Balanced Bone Drops: totally-balanced-bone-drops/about.md
      - Configuring Totally Balanced Bone Drops: totally-balanced-bone-drops/configuration.md
  - Utility Belt:
      - Introduction to Utility Belt: utility-belt/about.md
      - Configuring Utility Belt: utility-belt/configuration.md
  - Template Mod:
      - Getting Started: template-mod/getting-started.md

theme:
  name: material
  custom_dir: overrides
  logo: assets/JamCoreModding.png
  favicon: assets/JamCoreModding.png
  language: en

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.share
    - content.code.annotate
    
  palette:
    scheme: slate
    primary: red
    accent: pink

plugins:
  - search
  - social
  - git-revision-date-localized:
      type: timeago

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html

extra:
  homepage: https://github.com/JamCoreModding

  social:
    - icon: fontawesome/brands/discord
      link: https://discord.jamalam.tech
    - icon: fontawesome/brands/github
      link: https://github.com/JamCoreModding
    - icon: fontawesome/solid/feather
      link: https://maven.jamalam.tech
    - icon: fontawesome/solid/dollar-sign
      link: https://ko-fi.com/jamalamdev

