site_name: JamCore Mod Wiki
site_description: Information about JamCore Modding's mods and APIs.
site_url: https://docs.jamalam.tech/
site_author: The JamCore Modding Team

repo_url: https://github.com/JamCoreModding/docs
repo_name: JamCoreModding/docs

nav:
  - Home: index.md
  - Auto Recipe:
      - Introduction to Auto Recipe: auto-recipe/about.md
      - Getting Started with Auto Recipe: auto-recipe/getting-started.md
  - Totally Balanced Bone Drops:
      - Introduction to Totally Balanced Bone Drops: totally-balanced-bone-drops/about.md
      - Configuring Totally Balanced Bone Drops: totally-balanced-bone-drops/configuration.md

theme:
  name: material
  logo: assets/JamCoreModding.png
  favicon: assets/JamCoreModding.png
  language: en

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.share
    - content.code.annotate
    
  palette:
    scheme: slate
    primary: red
    accent: amber

plugins:
  - search
  - social
  - git-revision-date-localized:
      type: timeago

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  homepage: https://github.com/JamCoreModding

  social:
    - icon: fontawesome/brands/discord
      link: https://discord.jamalam.tech
    - icon: fontawesome/brands/github
      link: https://github.com/JamCoreModding
    - icon: fontawesome/solid/feather
      link: https://maven.jamalam.tech

