site_name: JamCore Mod Wiki
site_url: https://docs.jamalam.tech/

repo_url: https://github.com/JamCoreModding/docs
repo_name: JamCoreModding/docs

nav:
  - Home: index.md
  - About: about.md

theme:
  name: material
  logo: assets/JamCoreModding.png
  favicon: assets/JamCoreModding.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.share
  palette:
    scheme: slate
    primary: red
    accent: amber

plugins:
  - search
  - social

extra:
  homepage: https://github.com/JamCoreModding
